# Generated by Django 2.2.24 on 2022-01-04 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
