# Generated by Django 2.2.24 on 2022-01-04 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
